package corpus;

import org.springframework.web.bind.annotation.*;

@RestController
public class C52Lombok {
    @GetMapping("/c52")
    public String h(C52Person p) {
        p.setName("x");                        // generated by Lombok: nothing in source to follow
        return p.getName() + p.greeting();
    }
}
